# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'capston-inu-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'RxAppState'
  pod 'ReactorKit'
  pod 'SnapKit'
  pod 'GoogleSignIn'
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'FloatingPanel'

  use_frameworks!

  # Pods for capston-inu-iOS

  target 'capston-inu-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'capston-inu-iOSUITests' do
    # Pods for testing
  end

end
